/core/control:
  GearShiftControllerNode:
    ros__parameters:
      GSC_gear_omega_engine_min_table:
        - 0.0   # 1
        - 5000.0 # 2
        - 5000.0 # 3
        - 5000.0 # 4
        - 5000.0 # 5
        - 5000.0 # 6